Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/BlockLength:
  Include:
    - 'spec/**/*'

Style/BlockComments:
  Include:
    - 'spec/**/*'
