require 'pry'
require './station.rb'
require './route.rb'
require './train.rb'
require './train_pass.rb'
require './train_cargo.rb'
require './carriage.rb'
require './carriage_pass.rb'
require './carriage_cargo.rb'

